runtime: custom

env: flex

skip_files:
- node_modules/
- ^(.*/)?.*\.md$

# resources:
#   cpu: 2
#   memory_gb: 2.3
#   disk_size_gb: 10


# runtime_config:
#   operating_system: "ubuntu22"
#   runtime_version: "20"

# env_variables:
#   FOO: "BAR"

# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 5
#   max_instances: 100
#   min_pending_latency: 30ms
#   max_pending_latency: automatic
#   max_concurrent_requests: 50


# manual_scaling:
#   instances: 5